# Generated by Django 2.2.6 on 2019-12-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191102_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='Wheelchair'),
            preserve_default=False,
        ),
    ]
